[package]
name = "solana_spf_escrow_program"
version = "0.1.0"
edition = "2021"
license = "WTFPL"
publish = false

[dependencies]
solana-program = "2.2.1"
thiserror = "2.0.11"
spl-token = {version = "7.0.0", features = ["no-entrypoint"]}
arrayref = "0.3.6"

[lib]
crate-type = ["cdylib", "lib"]
